"""Approval bridge for the hermes-web-relay agent.

Forwards Claude Code ``PreToolUse`` approval requests to the relay
server so the operator can tap "allow" or "deny" on their phone. The
bridge is bound to a single :class:`RelayClient` and exposes a small
in-process API plus a tiny TCP loopback IPC server so the synchronous
``preToolUse`` hook script (a separate process spawned by Claude Code)
can request approvals without importing the agent's async machinery.

Wire-protocol decisions
-----------------------
* **Outbound (local -> server):** :attr:`Op.APPROVAL_REQUESTED` with
  ``ApprovalRequested`` payload (``prompt_id``, ``tool_name``,
  ``command``, ``context``). The ``prompt_id`` is a fresh uuid4 hex
  generated by :meth:`ApprovalBridge.request_approval`.
* **Inbound (server -> local):** :attr:`Op.APPROVAL_RESPOND` with
  ``ApprovalRespond`` payload (``prompt_id``, ``decision``, ``reason``).
  We resolve the matching in-process future with ``(decision, reason)``.

Concurrency model
-----------------
* A pending approval is represented by a single
  :class:`asyncio.Future` stored at ``self._pending[prompt_id]``.
* :meth:`request_approval` registers the future, sends the
  ``APPROVAL_REQUESTED`` frame, and awaits the future with a timeout.
* On timeout the future is cancelled and the function returns
  ``("deny", "timeout — defaulted to deny")`` so a stalled UI never
  silently allows a sensitive tool call.

IPC bridge
----------
The Claude Code ``PreToolUse`` hook is a synchronous shell script
(via ``preToolUse.py``) — it has no asyncio loop and cannot share
in-process state with the agent. We bridge that gap with a tiny
line-delimited JSON TCP server bound to ``127.0.0.1:15999`` (loopback
only — no external exposure). The hook opens a socket, writes one
``{"tool_name": ..., "command_string": ..., "context": ...}`` line,
reads back one ``{"continue": ..., "stop_reason": ...}`` line, and
exits. If the server is not running the hook defaults to allowing the
call (``{"continue": true}``) so the operator is never blocked just
because the agent is down.
"""

from __future__ import annotations

import asyncio
import json
import logging
import socket
import uuid
from typing import Any

from pydantic import BaseModel

from webrelay.agent.client import RelayClient
from webrelay.agent.protocol import (
    ApprovalRequested,
    ApprovalRespond,
    Envelope,
    Op,
)

_log = logging.getLogger(__name__)


# Default timeout for a single approval round-trip. 5 minutes matches
# the spec; if the operator's phone is offline the call should fail
# safe (deny) rather than hang the agent forever.
DEFAULT_TIMEOUT_S: float = 300.0

# TCP loopback address used by the preToolUse hook to talk to the
# running ApprovalBridge. Loopback only; the port is not exposed to
# other hosts.
IPC_HOST: str = "127.0.0.1"
IPC_PORT: int = 15999

# Default deny-reason returned when the user (or the IPC server) never
# answers. The em-dash matches the spec string.
_TIMEOUT_REASON = "timeout — defaulted to deny"


class ApprovalBridge:
    """Bridge approval requests from Claude Code to the relay server.

    One instance per agent process. The bridge owns a single
    :class:`RelayClient` (passed in), an in-memory map of pending
    :class:`asyncio.Future` objects keyed by ``prompt_id``, and a
    loopback TCP server that the synchronous ``preToolUse`` hook
    uses to ask for decisions.
    """

    def __init__(self, client: RelayClient) -> None:
        """Configure the bridge.

        Args:
            client: The relay client used both to register the
                inbound ``approval.respond`` handler and to push
                ``approval.requested`` frames to the server.
        """
        self._client = client
        # prompt_id -> Future[(decision, reason)]
        self._pending: dict[str, asyncio.Future[tuple[str, str | None]]] = {}
        # The IPC server task; created in :meth:`start`.
        self._ipc_server: asyncio.base_events.Server | None = None
        # Stash the loop for cli_entry() which runs in a fresh loop.
        self._loop: asyncio.AbstractEventLoop | None = None

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def start(self) -> None:
        """Register the inbound handler and start the IPC server.

        Safe to call once. Calling twice is a no-op for the handler
        registration (RelayClient will replace the prior binding per
        its own contract) but the IPC server would error, so we
        guard it.
        """
        self._client.register_handler(Op.APPROVAL_RESPOND, self.on_approval_respond)
        self._loop = asyncio.get_running_loop()
        self._ipc_server = await asyncio.start_server(
            self._handle_ipc_client,
            host=IPC_HOST,
            port=IPC_PORT,
        )
        _log.info(
            "approval bridge started: ipc=%s:%d", IPC_HOST, IPC_PORT
        )

    async def stop(self) -> None:
        """Close the IPC server and cancel any pending approvals.

        On shutdown we resolve any still-pending futures with a deny
        so the in-flight Claude Code call doesn't hang waiting for
        a response that will never come.
        """
        if self._ipc_server is not None:
            self._ipc_server.close()
            try:
                await self._ipc_server.wait_closed()
            except Exception:  # pragma: no cover - best effort
                pass
            self._ipc_server = None

        for future in list(self._pending.values()):
            if not future.done():
                future.set_result(("deny", _TIMEOUT_REASON))
        self._pending.clear()

    # ------------------------------------------------------------------
    # Inbound: approval.respond from the server
    # ------------------------------------------------------------------

    async def on_approval_respond(
        self, envelope: Envelope, payload: ApprovalRespond
    ) -> None:
        """Resolve the pending future for ``payload.prompt_id``.

        Decisions are normalized to lowercase ``"allow"`` / ``"deny"``
        so callers don't need to handle capitalization drift from the
        web UI. Unknown decisions are coerced to ``"deny"`` (fail
        closed) and logged.
        """
        prompt_id = payload.prompt_id
        future = self._pending.pop(prompt_id, None)
        if future is None:
            _log.warning(
                "approval bridge: received respond for unknown prompt_id=%s",
                prompt_id,
            )
            return

        decision_raw = (payload.decision or "").strip().lower()
        if decision_raw in ("allow", "deny"):
            decision: str = decision_raw
        else:
            _log.warning(
                "approval bridge: unknown decision %r, defaulting to deny",
                payload.decision,
            )
            decision = "deny"

        if not future.done():
            future.set_result((decision, payload.reason))

    # ------------------------------------------------------------------
    # Outbound: ask the server for a decision
    # ------------------------------------------------------------------

    async def request_approval(
        self,
        tool_name: str,
        command: str,
        context: str,
        *,
        timeout_s: float = DEFAULT_TIMEOUT_S,
    ) -> tuple[str, str | None]:
        """Send an ``approval.requested`` frame and await the answer.

        Args:
            tool_name: Name of the tool that needs approval
                (e.g. ``"Bash"``).
            command: The command string or short description of the
                action being requested.
            context: Free-form context (file path, reasoning, etc.).
            timeout_s: How long to wait before defaulting to deny.

        Returns:
            ``(decision, reason)``. ``decision`` is ``"allow"`` or
            ``"deny"``; ``reason`` is the operator-supplied reason
            from the web UI, or the timeout message when the call
            expires.
        """
        prompt_id = uuid.uuid4().hex
        loop = asyncio.get_running_loop()
        future: asyncio.Future[tuple[str, str | None]] = loop.create_future()
        self._pending[prompt_id] = future

        try:
            await self._client.send(
                Op.APPROVAL_REQUESTED,
                ApprovalRequested(
                    prompt_id=prompt_id,
                    tool_name=tool_name,
                    command=command,
                    context=context,
                ),
            )

            try:
                return await asyncio.wait_for(future, timeout=timeout_s)
            except asyncio.TimeoutError:
                _log.warning(
                    "approval bridge: timeout prompt_id=%s tool=%s",
                    prompt_id,
                    tool_name,
                )
                return ("deny", _TIMEOUT_REASON)
        finally:
            # Defensive: drop the future if it somehow survives.
            self._pending.pop(prompt_id, None)

    # ------------------------------------------------------------------
    # IPC: serve synchronous preToolUse.py over loopback TCP
    # ------------------------------------------------------------------

    async def _handle_ipc_client(
        self,
        reader: asyncio.StreamReader,
        writer: asyncio.StreamWriter,
    ) -> None:
        """Read one JSON line, ask for an approval, write one JSON line.

        The IPC protocol is intentionally minimal so the hook can
        implement it with stdlib only: a single newline-delimited
        JSON request, a single newline-delimited JSON response.

        Errors (malformed JSON, no ``tool_name`` field, etc.) return
        a deny response so the call is fail-closed.
        """
        try:
            try:
                raw = await reader.readline()
            except (ConnectionError, asyncio.IncompleteReadError):
                return

            if not raw:
                return

            try:
                request = json.loads(raw.decode("utf-8").strip() or "{}")
            except json.JSONDecodeError as exc:
                _log.warning("approval bridge ipc: bad json: %s", exc)
                await _write_ipc_response(
                    writer,
                    {"continue": False, "stop_reason": f"bad ipc request: {exc}"},
                )
                return

            tool_name = str(request.get("tool_name") or "")
            command = str(request.get("command_string") or "")
            context = str(request.get("context") or "")
            if not tool_name:
                _log.warning("approval bridge ipc: missing tool_name: %r", request)
                await _write_ipc_response(
                    writer,
                    {"continue": False, "stop_reason": "missing tool_name"},
                )
                return

            try:
                decision, reason = await self.request_approval(
                    tool_name=tool_name,
                    command=command,
                    context=context,
                )
            except Exception as exc:  # pragma: no cover - defensive
                _log.exception("approval bridge ipc: request_approval crashed")
                await _write_ipc_response(
                    writer,
                    {
                        "continue": False,
                        "stop_reason": f"approval bridge error: {exc}",
                    },
                )
                return

            if decision == "allow":
                await _write_ipc_response(writer, {"continue": True})
            else:
                stop_reason = reason or "denied by operator"
                await _write_ipc_response(
                    writer,
                    {"continue": False, "stop_reason": stop_reason},
                )
        finally:
            try:
                writer.close()
                await writer.wait_closed()
            except Exception:  # pragma: no cover - best effort
                pass

    # ------------------------------------------------------------------
    # Synchronous CLI entry for the preToolUse hook
    # ------------------------------------------------------------------

    def cli_entry(self) -> None:
        """Synchronous entry point invoked by the preToolUse hook.

        Reads a single hook input from stdin (Claude Code's standard
        ``PreToolUse`` JSON format), dials the in-process IPC server
        over loopback, and prints the matching response JSON. If the
        agent isn't running we default to ``{"continue": true}`` so
        work is never blocked just because the relay is offline.
        """
        try:
            raw = ""
            try:
                raw = sys_stdin_read()
            except Exception:  # pragma: no cover - stdin can be weird
                raw = ""

            tool_name = ""
            command = ""
            context = ""
            if raw:
                try:
                    hook_input = json.loads(raw)
                except json.JSONDecodeError:
                    hook_input = {}
                if isinstance(hook_input, dict):
                    tool_name = str(hook_input.get("tool_name") or "")
                    command = str(hook_input.get("command_string") or "")
                    context = str(hook_input.get("context") or "")

            if not tool_name:
                # Nothing useful to forward; allow.
                print(json.dumps({"continue": True}))
                return

            response = _ipc_request_sync(
                IPC_HOST,
                IPC_PORT,
                {
                    "tool_name": tool_name,
                    "command_string": command,
                    "context": context,
                },
            )
            print(json.dumps(response))
        except Exception as exc:  # pragma: no cover - last-resort net
            # Never crash the hook; allow on any unexpected error.
            print(
                json.dumps(
                    {"continue": True, "stop_reason": f"hook fallback: {exc}"}
                )
            )


# ---------------------------------------------------------------------------
# Module-level helpers (importable from tests and the hook script)
# ---------------------------------------------------------------------------


async def _write_ipc_response(
    writer: asyncio.StreamWriter, response: dict[str, Any]
) -> None:
    """Write a single newline-delimited JSON response and flush."""
    payload = (json.dumps(response) + "\n").encode("utf-8")
    writer.write(payload)
    try:
        await writer.drain()
    except Exception:  # pragma: no cover - best effort
        pass


def sys_stdin_read() -> str:
    """Read all of stdin. Wrapped for testability."""
    import sys

    return sys.stdin.read()


def _ipc_request_sync(
    host: str, port: int, payload: dict[str, Any], timeout_s: float = 10.0
) -> dict[str, Any]:
    """Blocking loopback IPC client used by the synchronous hook.

    Opens a TCP socket to ``host:port``, writes one JSON line, reads
    one JSON line, and returns the parsed response dict. On any
    failure (refused, timed out, malformed) returns
    ``{"continue": True}`` so the hook fails open when the agent is
    offline.
    """
    sock: socket.socket | None = None
    try:
        sock = socket.create_connection((host, port), timeout=timeout_s)
        sock.settimeout(timeout_s)
        data = (json.dumps(payload) + "\n").encode("utf-8")
        sock.sendall(data)
        # Read until newline (or EOF).
        buf = bytearray()
        while True:
            chunk = sock.recv(4096)
            if not chunk:
                break
            buf.extend(chunk)
            if b"\n" in buf:
                break
        if not buf:
            return {"continue": True}
        line = bytes(buf).split(b"\n", 1)[0]
        try:
            response = json.loads(line.decode("utf-8"))
        except json.JSONDecodeError:
            return {"continue": True}
        if not isinstance(response, dict):
            return {"continue": True}
        return response
    except (OSError, socket.timeout):
        return {"continue": True}
    finally:
        if sock is not None:
            try:
                sock.close()
            except OSError:  # pragma: no cover - best effort
                pass


__all__ = [
    "ApprovalBridge",
    "DEFAULT_TIMEOUT_S",
    "IPC_HOST",
    "IPC_PORT",
]
